/* FINDZIA_SUPPORT_RELEASE=156.7.62 — a grounded site assistant, separate from shopping. */
(()=>{'use strict';
 const KNOWLEDGE=/* SUPPORT_KNOWLEDGE */ null;
 const COPY={
  badge:['FINDZIA ASSIST','مساعد FINDZIA'],title:['How can I help?','شلون أقدر أساعدك؟'],intro:['A little guidance for your next find. Ask about searching, credits or your account.','كل اللي تحتاجه لاكتشافك القادم. اسأل عن البحث، الرصيد أو حسابك.'],common:['Common questions','أسئلة شائعة'],placeholder:['Ask about Findzia…','اسأل عن Findzia…'],send:['Send message','إرسال الرسالة'],stop:['Stop response','إيقاف الرد'],thinking:['Finding an answer…','أجهّز لك الإجابة…'],retry:['Try again','حاول مجددًا'],error:['Could not connect. Try again or contact support.','تعذّر الاتصال. حاول مجددًا أو تواصل مع الدعم.'],limited:['Please wait a minute before sending another question.','انتظر دقيقة قبل إرسال سؤال آخر.'],stopped:['Response stopped. You can retry this question.','توقف الرد. تقدر تعيد إرسال هالسؤال.'],contact:['Contact support','تواصل مع الدعم'],note:['AI help for Findzia · No search credits used','مساعدة ذكية عن Findzia · بدون خصم رصيد'],you:['You','أنت'],assistant:['Findzia assistant','مساعد Findzia'],newChat:['New conversation','محادثة جديدة'],plans:['View search packs','عرض باقات البحث'],usage:['Your search credits','رصيد البحث'],home:['My account','حسابي'],settings:['Settings','الإعدادات'],activity:['My activity','نشاطي'],refund:['Refund Policy','سياسة الاسترجاع'],privacy:['Privacy Policy','سياسة الخصوصية'],new_search:['Back to search','العودة للبحث'],guide:['Findzia guide','دليل Findzia']
 };
 const el=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;};
 function glyph(kind){const s=document.createElementNS('http://www.w3.org/2000/svg','svg');s.setAttribute('viewBox','0 0 24 24');s.setAttribute('fill','none');s.setAttribute('stroke','currentColor');s.setAttribute('stroke-width','1.6');s.setAttribute('stroke-linecap','round');s.setAttribute('stroke-linejoin','round');s.setAttribute('aria-hidden','true');s.innerHTML=kind==='send'?'<path d="M12 19V5m-6 6 6-6 6 6"/>':kind==='stop'?'<rect x="7" y="7" width="10" height="10" rx="2"/>':kind==='mail'?'<rect x="3" y="5" width="18" height="14" rx="4"/><path d="m4 7 8 6 8-6"/>':'<path d="m12 3 2.4 6.6L21 12l-6.6 2.4L12 21l-2.4-6.6L3 12l6.6-2.4ZM20 2v4m-2-2h4"/>';return s;}
 function create(root){
  const state={messages:[],draft:'',flight:null,host:null,options:null,detach:null};let refs=null;
  const t=k=>{const a=COPY[k]||[k,k];return window.FindziaI18n?.t(a[0],a[1],root)||(root.dataset.lang==='ar'?a[1]:a[0]);};
  const question=topic=>window.FindziaI18n?.t(topic.en.question,topic.ar.question,root)||(root.dataset.lang==='ar'?topic.ar.question:topic.en.question);
  function button(text,fn,cls){const b=el('button',cls,text);b.type='button';b.addEventListener('click',fn);return b;}
  function abort(message=false){if(!state.flight)return;const job=state.flight;state.flight=null;job.controller.abort();clearTimeout(job.timer);job.message.failed='stopped';if(refs)paint();}
  function viewport(){const dialog=state.host?.closest('dialog');if(!dialog)return;const vv=window.visualViewport;dialog.style.setProperty('--fzs-viewport-height',(vv?.height||innerHeight)+'px');dialog.style.setProperty('--fzs-viewport-top',(vv?.offsetTop||0)+'px');}
  state.detach=()=>{abort();state.host=null;refs=null;window.visualViewport?.removeEventListener('resize',viewport);window.visualViewport?.removeEventListener('scroll',viewport);};
  state.clear=()=>{state.detach();state.messages=[];state.draft='';};
  root.addEventListener('fz:account-session',state.clear);
  window.addEventListener('pagehide',()=>{abort();state.messages=[];state.draft='';if(refs)paint();});
  function action(id){if(['home','plans','usage','activity','settings'].includes(id))return button(t(id),()=>state.options.open(id),'fzs-action');
   if(id==='new_search')return button(t(id),()=>{state.options.close();root.fzRefineBridge?.newSearch?.();},'fzs-action');
   const href={contact:'mailto:info@findzia.com',refund:'/policies/refund-policy',privacy:'/policies/privacy-policy'}[id];if(!href)return null;const a=el('a','fzs-action',t(id));a.href=href;if(id!=='contact'){a.target='_blank';a.rel='noopener';}return a;
  }
  function scroll(){if(!state.host)return;const body=state.host.parentElement;requestAnimationFrame(()=>{if(state.host)body.scrollTo({top:body.scrollHeight,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});});}
  function paint(){if(!refs)return;const {host,log,topics,status,send,reset}=refs;host.classList.toggle('has-chat',state.messages.length>0);reset.hidden=!state.messages.length;topics.open=!state.messages.length;
   const keep=new Set();for(const [index,m]of state.messages.entries()){const signature=JSON.stringify(m);let row=refs.rows.get(m);if(row?.signature===signature){keep.add(row.node);if(log.children[index]!==row.node)log.insertBefore(row.node,log.children[index]||null);continue;}const item=el('div','fzs-message fzs-'+m.role);item.setAttribute('translate','no');item.dir='auto';item.append(el('span','fzs-speaker',t(m.role==='user'?'you':m.mode==='guide'?'guide':'assistant')),el('p','',m.content));if(m.actions?.length){const actions=el('div','fzs-actions');m.actions.forEach(id=>{const a=action(id);if(a)actions.append(a);});item.append(actions);}if(m.failed){item.append(el('p','fzs-error',t(m.failed)),button(t('retry'),()=>sendQuestion(m.content,m.topic,m),'fzs-retry'));}if(row)row.node.replaceWith(item);else log.insertBefore(item,log.children[index]||null);refs.rows.set(m,{signature,node:item});keep.add(item);}
   for(const child of [...log.children])if(!keep.has(child))child.remove();
   status.hidden=!state.flight;status.textContent=state.flight?t('thinking'):'';send.replaceChildren(glyph(state.flight?'stop':'send'));send.setAttribute('aria-label',t(state.flight?'stop':'send'));send.disabled=!state.flight&&!refs.input.value.trim();
  }
  async function sendQuestion(value,topic,retryMessage){
   const text=String(value||'').trim();if(state.flight||!text||text.length>1200)return;
   const history=state.messages.filter(m=>!m.failed&&m!==retryMessage).slice(-6).map(m=>({role:m.role,content:m.content.slice(0,1800)}));
   const message=retryMessage||{role:'user',content:text,topic};delete message.failed;if(!retryMessage)state.messages.push(message);state.messages=state.messages.slice(-24);
   state.draft='';if(refs){refs.input.value='';refs.input.style.height='auto';}
   const job={message,controller:new AbortController(),timer:null};state.flight=job;paint();scroll();job.timer=setTimeout(()=>job.controller.abort(),18000);
   try{
    const res=await fetch(state.options.api+'/api/support/chat',{method:'POST',credentials:'omit',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:text,language:root.dataset.lang||'en',history,topic}),signal:job.controller.signal});
    if(!res.ok){const error=Error('support');error.status=res.status;throw error;}
    const data=await res.json();if(!data.ok||typeof data.answer!=='string'||!data.answer.trim()||data.answer.length>1800)throw Error('support');if(state.flight!==job)return;
    if(data.mode==='unavailable')message.failed='error';else state.messages.push({role:'assistant',content:data.answer,actions:Array.isArray(data.actions)?data.actions.filter(x=>typeof x==='string').slice(0,3):[],mode:data.mode});
   }catch(e){if(state.flight===job)message.failed=e.status===429?'limited':'error';}
   finally{clearTimeout(job.timer);if(state.flight===job){state.flight=null;paint();scroll();}}
  }
  state.mount=(body,options)=>{state.options=options;const host=el('section','fzs');state.host=host;body.append(host);
   const intro=el('div','fzs-intro'),mark=el('div','fzs-mark');mark.append(glyph('spark'));const head=el('div','fzs-heading');head.append(el('p','fzs-badge',t('badge')),el('h3','',t('title')));const reset=button('',()=>{abort();state.messages=[];state.draft='';refs.input.value='';paint();},'fzs-reset');reset.setAttribute('aria-label',t('newChat'));reset.title=t('newChat');reset.textContent='↻';intro.append(mark,head,reset,el('p','fzs-description',t('intro')));
   const topics=el('details','fzs-topics');topics.open=true;topics.append(el('summary','',t('common')));const grid=el('div','fzs-questions');for(const topic of KNOWLEDGE.topics.slice(0,6)){const b=button(question(topic),()=>sendQuestion(question(topic),topic.id),'fzs-question');b.dataset.supportTopic=topic.id;grid.append(b);}topics.append(grid);
   const log=el('div','fzs-log');log.setAttribute('role','log');log.setAttribute('aria-live','polite');log.setAttribute('aria-relevant','additions');log.setAttribute('aria-label',t('assistant'));const status=el('p','fzs-thinking');status.setAttribute('role','status');status.hidden=true;
   const bottom=el('div','fzs-bottom'),form=el('form','fzs-form'),input=el('textarea','fzs-input');input.rows=1;input.maxLength=1200;input.dir='auto';input.placeholder=t('placeholder');input.setAttribute('aria-label',t('placeholder'));input.value=state.draft;
   const send=el('button','fzs-send');send.type='submit';send.append(glyph('send'));send.setAttribute('aria-label',t('send'));form.append(input,send);const foot=el('div','fzs-foot'),contact=el('a','fzs-contact');contact.href='mailto:info@findzia.com';contact.append(glyph('mail'),el('span','',t('contact')));foot.append(el('span','',t('note')),contact);bottom.append(form,foot);
   host.append(intro,topics,log,status,bottom);refs={host,log,topics,status,send,input,reset,rows:new WeakMap()};
   input.addEventListener('input',()=>{state.draft=input.value;input.style.height='auto';input.style.height=Math.min(input.scrollHeight,110)+'px';send.disabled=!state.flight&&!input.value.trim();});
   input.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();if(!state.flight)sendQuestion(input.value);}});
   form.addEventListener('submit',e=>{e.preventDefault();if(state.flight)abort(true);else sendQuestion(input.value);});
   paint();viewport();window.visualViewport?.addEventListener('resize',viewport);window.visualViewport?.addEventListener('scroll',viewport);if(state.messages.length)scroll();
  };
  return state;
 }
 const style=el('style');style.textContent=`
 .fzs{display:flex;flex-direction:column;min-height:100%;gap:22px;color:var(--a-ink)}.fzs-intro{display:grid;grid-template-columns:52px 1fr auto;align-items:center;gap:14px}.fzs-mark{width:52px;height:52px;display:grid;place-items:center;border-radius:18px;background:var(--a-soft);border:1px solid var(--a-line);color:var(--a-accent)}.fzs-mark svg{width:28px;height:28px}.fzs-badge{font-size:10px;letter-spacing:.12em;font-weight:650;color:var(--a-muted);margin:0 0 5px}.fzs-heading h3{font-size:25px!important;line-height:1.25;letter-spacing:-.6px;margin:0;font-weight:600}.fzs-description{grid-column:1/-1;font-size:14px;line-height:1.7;color:var(--a-muted);margin:0;max-width:420px}.fzs-reset{width:38px;height:38px;border:1px solid var(--a-line);background:var(--a-bg);color:var(--a-muted);border-radius:50%;font-size:22px!important}
 .fzs-topics>summary{font-size:12px;color:var(--a-muted);cursor:pointer;padding:4px 0 12px}.fzs-questions{display:grid;grid-template-columns:1fr 1fr;gap:9px}.fzs-question{position:relative;min-height:72px;text-align:start;border:1px solid var(--a-line);border-radius:14px;background:var(--a-bg);color:var(--a-ink);padding:13px 14px;font-size:13px!important;line-height:1.5!important;transition:background .18s,transform .18s,border-color .18s}.fzs-question:hover{background:var(--a-soft);border-color:var(--a-muted)}.fzs-question:active{transform:scale(.975)}.fzs-log{display:flex;flex-direction:column;gap:20px}.fzs-log:empty{display:none}.fzs-message{max-width:96%;min-width:0;overflow-wrap:anywhere;font-size:14px;line-height:1.8}.fzs-message p{margin:0;white-space:pre-wrap}.fzs-speaker{display:block;font-size:11px;color:var(--a-muted);margin-bottom:5px}.fzs-user{align-self:flex-end;background:var(--a-soft);border:1px solid var(--a-line);border-radius:17px 17px 4px 17px;padding:11px 15px}.fzs-assistant{align-self:flex-start;padding:2px 0}.fzs-assistant>.fzs-speaker{color:var(--a-accent);font-weight:600}.fzs-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}.fzs-action{display:inline-flex;align-items:center;min-height:36px;border:1px solid var(--a-line);border-radius:9px;background:var(--a-bg);color:var(--a-ink);text-decoration:none;padding:7px 11px;font-size:12px!important;line-height:1.4}.fzs-action:hover{background:var(--a-soft)}.fzs-thinking{margin:0;color:var(--a-muted);font-size:13px}.fzs-thinking:before{content:'';display:inline-block;width:6px;height:6px;background:var(--a-accent);border-radius:50%;margin-inline-end:8px;animation:fzs-pulse 1s ease-in-out infinite alternate}.fzs-error{color:var(--a-muted);font-size:12px;margin-top:10px!important}.fzs-retry{border:0;background:none;color:var(--a-ink);text-decoration:underline;font-size:12px!important;padding:8px 0}
 .fzs-bottom{position:sticky;bottom:-24px;margin-top:auto;padding:14px 0 8px;background:var(--a-bg);box-shadow:0 -10px 18px var(--a-bg)}.fzs-form{display:flex;align-items:flex-end;gap:10px;border:1px solid var(--a-line);border-radius:20px;background:var(--a-soft);padding:9px}.fzs-form:focus-within{border-color:var(--a-accent);box-shadow:0 0 0 3px color-mix(in srgb,var(--a-accent) 10%,transparent)}.fzs-input{font:inherit;font-size:16px!important;line-height:1.5;min-height:44px;max-height:110px;width:100%;flex:1;min-width:0;padding:10px 7px;border:0;resize:none;outline:none!important;background:none;color:var(--a-ink);box-shadow:none!important;border-radius:0}.fzs-input::placeholder{color:var(--a-muted);opacity:.85}.fzs-send{display:grid;place-items:center;border:0;background:var(--a-accent);color:var(--a-bg);width:44px;height:44px;border-radius:14px;flex:none;transition:transform .16s}.fzs-send:active{transform:scale(.94)}.fzs-foot{display:flex;align-items:center;justify-content:space-between;gap:10px;flex-wrap:wrap;padding:11px 2px 0;color:var(--a-muted);font-size:10px;line-height:1.5}.fzs-contact{display:inline-flex;align-items:center;gap:5px;text-decoration:none;min-height:28px;font-size:11px}.fzs-contact svg{width:14px;height:14px}.fzs.has-chat{gap:18px}.fzs.has-chat .fzs-heading h3{font-size:18px!important;letter-spacing:0}.fzs.has-chat .fzs-description{display:none}.fzs.has-chat .fzs-topics>summary{padding-bottom:0}.fzs.has-chat .fzs-topics[open] summary{padding-bottom:12px}.fz-account[dir=rtl] .fzs-badge{letter-spacing:0}.fz-account[dir=rtl] .fzs-user{border-radius:17px 17px 17px 4px}
 @keyframes fzs-pulse{to{opacity:.35;transform:scale(.7)}}@media(max-width:600px){.fz-account[data-view=ask]{height:min(100dvh,var(--fzs-viewport-height,100dvh));max-height:min(100dvh,var(--fzs-viewport-height,100dvh));top:var(--fzs-viewport-top,0px);bottom:auto}.fzs-bottom{bottom:-22px;padding-bottom:max(8px,env(safe-area-inset-bottom))}.fzs-heading h3{font-size:23px!important}.fzs-foot{justify-content:center;text-align:center}.fzs-questions{gap:8px}}@media(prefers-reduced-motion:reduce){.fzs *{animation:none!important;transition:none!important}}
 `;document.head.append(style);
 window.FindziaSupport={mount(root,body,options){root.fzSupport??=create(root);root.fzSupport.mount(body,options);}};
})();
